#!/usr/bin/env python3
"""
Fetches the two typefaces from Google and writes them into fonts/, so the
deployed site serves its own type and no visitor's browser ever contacts a
Google server to read a page. That is a privacy requirement before it is a
performance one — a third-party font request carries the visitor's IP and
referrer, which is exactly what a consent notice would otherwise have to cover.

    python3 _build/fetch_fonts.py

Writes: fonts/*.woff2 and _build/fonts.css (the @font-face block build.py
prepends to the stylesheet). Run it again only to take a font update; the
output is committed, so an ordinary build needs no network.
"""
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "fonts"

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

API = ("https://fonts.googleapis.com/css2"
       "?family=Inter:wght@300..800"
       "&family=Plus+Jakarta+Sans:ital,wght@0,500..800;1,500..600"
       "&display=swap")

# Only the alphabets the site is written in. Greek and Vietnamese are dropped.
# Plus Jakarta Sans has no basic-Cyrillic subset at all — cyrillic-ext without
# it covers nothing Russian — so the Russian display face falls through to
# Inter, which is what the font stack already says it should do.
KEEP = {
    "Inter": {"latin", "latin-ext", "cyrillic", "cyrillic-ext"},
    "Plus Jakarta Sans": {"latin", "latin-ext"},
}

BLOCK = re.compile(r"/\* (?P<subset>[\w-]+) \*/\s*@font-face \{(?P<body>[^}]*)\}")


def field(body, name):
    m = re.search(name + r":\s*([^;]+);", body)
    return m.group(1).strip() if m else None


def get(url, binary=False):
    """curl rather than urllib: the system Python here has no CA bundle of its
    own, and curl is present wherever this would be run."""
    out = subprocess.run(
        ["curl", "-sSfL", "--max-time", "30", "-A", UA, url],
        check=True, capture_output=True).stdout
    return out if binary else out.decode("utf-8")


def main():
    OUT.mkdir(exist_ok=True)
    css = get(API)
    faces, kept = [], set()

    for m in BLOCK.finditer(css):
        subset, body = m.group("subset"), m.group("body")
        family = field(body, "font-family").strip("'\"")
        if subset not in KEEP.get(family, ()):
            continue
        style = field(body, "font-style")
        weight = field(body, "font-weight")
        rng = field(body, "unicode-range")
        src = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)

        stem = family.lower().replace(" ", "-").replace("plus-jakarta-sans", "jakarta")
        name = "%s-%s%s.woff2" % (stem, subset, "-italic" if style == "italic" else "")
        (OUT / name).write_bytes(get(src, binary=True))
        kept.add(name)
        print("  %-34s %6.1f KB" % (name, (OUT / name).stat().st_size / 1024))

        faces.append(
            "@font-face {\n"
            "  font-family: '%s';\n"
            "  font-style: %s;\n"
            "  font-weight: %s;\n"
            "  font-display: swap;\n"
            "  src: url(../fonts/%s) format('woff2');\n"
            "  unicode-range: %s;\n"
            "}" % (family, style, weight, name, rng))

    for stale in OUT.glob("*.woff2"):
        if stale.name not in kept:
            stale.unlink()
            print("  removed stale", stale.name)

    (ROOT / "_build" / "fonts.css").write_text(
        "/* Self-hosted — generated by _build/fetch_fonts.py, do not edit. */\n"
        + "\n".join(faces) + "\n", encoding="utf-8")
    print("\n%d faces, %.0f KB total" % (
        len(faces), sum(f.stat().st_size for f in OUT.glob("*.woff2")) / 1024))


if __name__ == "__main__":
    main()
